### PR TITLE
add Coastal Informatics to oss-directory

### PR DESCRIPTION
**Pull request by danwild**

### CODE REVIEW

**Comment by jmp75** [comment]
Sorry I overlooked to get back to this last year. Thank you Dan.

**Comment by danwild** [comment]
No worries @jmp75, did u mean to merge this?

**Comment by danwild** [comment]
Bump 😅

**Comment by jmp75** [comment]
@danwild thank you for the reminder. I must have been sleep deprived to mess that up and miss the notification. Now done finally

**Pull request closed without merging**
